const CONFIG = {
  RENDER_W: 960,
  RENDER_H: 540,
  FPS: 60,

  TITLE: "BAKUGO'S LOCATION",

  DUOTONE_SHADOW: [2, 4, 18],
  DUOTONE_HIGHLIGHT: [90, 140, 255],
  GLOW_COLOR: [110, 160, 255],
  TEXT_COLOR: [150, 190, 255],
  TEXT_COLOR_SELECTED: [235, 245, 255],

  VHS_LINE_STEP: 4,
  VHS_LINE_OPACITY: 60,
  VHS_HEAVY_BAR_CHANCE: 0.10,
  VHS_GLITCH_BAR_CHANCE: 0.035,
  SCAN_SWEEP_SPEED: 40,
  SCAN_SWEEP_HEIGHT: 30,
  CHROMA_ABERRATION_PX: 2,
  JITTER_MAX_PX: 3,

  FLASH_CHARACTERS: [
    { name: "bakugo",  file: "assets/images/char_bakugo.png",  weight: 5 },
    { name: "diavolo", file: "assets/images/char_diavolo.png", weight: 4 },
    { name: "lucifer", file: "assets/images/char_lucifer.png", weight: 4 },
  ],
  EASTER_EGG_CHARACTER: { name: "easter_egg", file: "assets/images/char_easter_egg.png" },
  EASTER_EGG_CHANCE: 0.05,

  FLASH_MIN_HOLD: 0.9,
  FLASH_MAX_HOLD: 2.6,
  FLASH_TRANSITION_TIME: 0.08,

  PORTRAIT_MAX_HEIGHT: 729,
  PORTRAIT_ANCHOR_X: 19,
  PORTRAIT_ANCHOR_Y: -54,

  MENU_ITEMS: ["NEW GAME", "CONTINUE GAME", "EXIT"],
  MENU_FONT_SIZE: 22,
  TITLE_FONT_SIZE: 40,
  MENU_LINE_SPACING: 46,
  MENU_ANCHOR_X: 538,
  MENU_ANCHOR_Y: 216,
  MENU_PULSE_SPEED: 3.2,

  TITLE_ANCHOR_Y: 486,
  TITLE_SWAY_X_PX: 4,
  TITLE_SWAY_Y_PX: 3,
  TITLE_SWAY_SPEED: 1.8,

  OFFICE_W: 1000,
  OFFICE_H: 480,
  OFFICE_IMG_DIR: "assets/images/office",

  DOOR_BUTTON_HALF_SIZE: 45,
  SHOCK_BUTTON_HALF_SIZE: 45,

  LEFT_DOOR_BUTTON_POS: [208, 236],
  RIGHT_DOOR_BUTTON_POS: [791, 236],
  RIGHT_SHOCK_BUTTON_POS: [677, 241],
  LEFT_SHOCK_BUTTON_POS: [323, 241],

  DOOR_FRAME_HOLD: 0.09,
  DOOR_GLOW_MAX_ALPHA: 235,

  CENTER_HALLWAY_RECT: [350, 90, 300, 390],
  SHOCK_FLASH_DURATION: 0.35,
  SHOCK_COOLDOWN: 1.2,
  SHOCK_FLASH_COLOR: [140, 200, 255],
  SHOCK_FLASH_MAX_ALPHA: 150,
  SHOCK_GLOW_MAX_ALPHA: 235,

  MENU_AUDIO: "assets/audio/menu.ogg",
  CUTSCENE_AUDIO: "assets/audio/cutscene.ogg",
  CUTSCENE_DURATION: 57.0,
  CUTSCENE_FADE_IN: 1.5,
  CUTSCENE_FADE_OUT: 1.2,
  CUTSCENE_ECHO_ENABLED: true,
  CUTSCENE_ECHO_TAPS: 3,
  CUTSCENE_ECHO_DELAY: 0.42,
  CUTSCENE_ECHO_DECAY: 0.55,

  SAVE_KEY: "fnaf_bakugo_save",
};
